name: Publish - crates.io

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Crates.io
    environment: crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Formatting
        run: |
          rustup component add rustfmt
          cargo fmt --all --manifest-path rust/Cargo.toml -- --check
          
      - name: Run unit tests
        run: cargo test --workspace --manifest-path=rust/Cargo.toml -- --skip test_e2e

      - name: Publish bambam-core
        run: cargo publish -p bambam-core --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"
      
      - name: Publish bambam-osm
        run: cargo publish -p bambam-osm --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

      - name: Publish bambam-gtfs
        run: cargo publish -p bambam-gtfs --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

      - name: Publish bambam-gbfs
        run: cargo publish -p bambam-gbfs --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

      - name: Publish bambam-omf
        run: cargo publish -p bambam-omf --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

      - name: Publish bambam
        run: cargo publish -p bambam --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

#       - name: Publish bambam-py
#         run: cargo publish -p bambam-py --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"
